# Generated by Django 5.2.1 on 2025-06-02 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='duration',
            field=models.IntegerField(blank=True, help_text='Kurs davomiyligi soatlarda', null=True),
        ),
    ]
