# Generated by Django 5.2.1 on 2025-06-02 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0002_alter_courses_duration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='birth_date',
        ),
        migrations.AddField(
            model_name='student',
            name='birth_day',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
